name: Example
on:
  push:
    branches: [ master ]

jobs:
      
      example:
                runs-on: ubuntu-latest 
                permissions:
                        contents: write
                steps:
                  - uses: lowlighter/metrics@latest

                    with:
                      
                      filename: metrics.repository.svg
                      token: ${{ secrets.GH_TOKEN }}
                      template: repository
                      repo: dwm
                      base: header
                      plugin_introduction: yes
