name: Example
on:
  push:
    branches: [ master ]

jobs:
      uses: lowlighter/metrics@latest
      filename: metrics.repository.svg
      token: ${{ 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 }}
      template: repository
      repo: metrics
      base: header
      plugin_introduction: yes
