name: Metrics
on:
  schedule: 
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_activity: yes
          plugin_repositories: yes
          plugin_community: yes
