name: Example
on:
  push:
    branches: [ master ]

jobs:
      
      example:
                runs-on: ubuntu-latest 
                permissions:
                        contents: write
                steps:
                  - uses: lowlighter/metrics@latest

                    with:
                      
                      filename: metrics.repository.svg
                      token: ${{ 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 }}
                      template: repository
                      repo: dwm
                      base: header
                      plugin_introduction: yes
